// 2027 U.S. Election Calendar — race data
// Confidence: "confirmed" = sourced to an official calendar or authoritative report.
//             "projected" = derived from statute; no official 2027 calendar published yet.
// As of July 2026. Primaries are largely projected because no state has posted a 2027 calendar.

const RACES = [
  // ---------- GOVERNORS ----------
  { id:'ky-gov', tier:'Statewide executive', cat:'Governor', state:'Kentucky', st:'KY',
    office:'Governor', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Andy Beshear (D)', status:'Term-limited — OPEN SEAT', hold:'D', open:true,
    note:'Governor and Lieutenant Governor run as a joint ticket.' },
  { id:'la-gov', tier:'Statewide executive', cat:'Governor', state:'Louisiana', st:'LA',
    office:'Governor', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'Jeff Landry (R)', status:'Eligible — first term', hold:'R', open:false,
    note:'Jungle primary Oct 9; runoff Nov 20 only if no candidate clears 50%.' },
  { id:'ms-gov', tier:'Statewide executive', cat:'Governor', state:'Mississippi', st:'MS',
    office:'Governor', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Tate Reeves (R)', status:'Term-limited — OPEN SEAT', hold:'R', open:true,
    note:'State Auditor Shad White and Ag Commissioner Andy Gipson are both running.' },

  // ---------- KENTUCKY DOWN-BALLOT ----------
  { id:'ky-lg', tier:'Statewide executive', cat:'Other statewide', state:'Kentucky', st:'KY',
    office:'Lieutenant Governor', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Jacqueline Coleman (D)', status:'Ticket term-limited', hold:'D', open:true },
  { id:'ky-ag', tier:'Statewide executive', cat:'Other statewide', state:'Kentucky', st:'KY',
    office:'Attorney General', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Russell Coleman (R)', status:'Eligible — first term', hold:'R', open:false },
  { id:'ky-sos', tier:'Statewide executive', cat:'Other statewide', state:'Kentucky', st:'KY',
    office:'Secretary of State', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Michael Adams (R)', status:'Term-limited — OPEN SEAT', hold:'R', open:true },
  { id:'ky-aud', tier:'Statewide executive', cat:'Other statewide', state:'Kentucky', st:'KY',
    office:'Auditor of Public Accounts', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Allison Ball (R)', status:'Eligible', hold:'R', open:false },
  { id:'ky-tre', tier:'Statewide executive', cat:'Other statewide', state:'Kentucky', st:'KY',
    office:'Treasurer', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Mark Metcalf (R)', status:'Eligible', hold:'R', open:false },
  { id:'ky-ag2', tier:'Statewide executive', cat:'Other statewide', state:'Kentucky', st:'KY',
    office:'Commissioner of Agriculture', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Jonathan Shell (R)', status:'Eligible', hold:'R', open:false },

  // ---------- LOUISIANA DOWN-BALLOT ----------
  { id:'la-lg', tier:'Statewide executive', cat:'Other statewide', state:'Louisiana', st:'LA',
    office:'Lieutenant Governor', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'Billy Nungesser (R)', status:'Eligible — no term limit', hold:'R', open:false },
  { id:'la-ag', tier:'Statewide executive', cat:'Other statewide', state:'Louisiana', st:'LA',
    office:'Attorney General', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'Liz Murrill (R)', status:'Eligible — no term limit', hold:'R', open:false },
  { id:'la-sos', tier:'Statewide executive', cat:'Other statewide', state:'Louisiana', st:'LA',
    office:'Secretary of State', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'Nancy Landry (R)', status:'Eligible — no term limit', hold:'R', open:false },
  { id:'la-tre', tier:'Statewide executive', cat:'Other statewide', state:'Louisiana', st:'LA',
    office:'Treasurer', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'John Fleming (R)', status:'Eligible — no term limit', hold:'R', open:false },
  { id:'la-agr', tier:'Statewide executive', cat:'Other statewide', state:'Louisiana', st:'LA',
    office:'Commissioner of Agriculture & Forestry', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'Mike Strain (R)', status:'Eligible — no term limit', hold:'R', open:false },
  { id:'la-ins', tier:'Statewide executive', cat:'Other statewide', state:'Louisiana', st:'LA',
    office:'Commissioner of Insurance', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'Tim Temple (R)', status:'Eligible — no term limit', hold:'R', open:false },

  // ---------- MISSISSIPPI DOWN-BALLOT ----------
  { id:'ms-lg', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Lieutenant Governor', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Delbert Hosemann (R)', status:'Term-limited — OPEN SEAT', hold:'R', open:true,
    note:'Secretary of State Michael Watson reportedly eyeing this seat.' },
  { id:'ms-ag', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Attorney General', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Lynn Fitch (R)', status:'Eligible', hold:'R', open:false },
  { id:'ms-sos', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Secretary of State', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Michael Watson (R)', status:'Eligible', hold:'R', open:false },
  { id:'ms-tre', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Treasurer', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'David McRae (R)', status:'Eligible', hold:'R', open:false },
  { id:'ms-aud', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Auditor', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Shad White (R)', status:'Running for Governor — OPEN SEAT', hold:'R', open:true },
  { id:'ms-agr', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Commissioner of Agriculture & Commerce', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Andy Gipson (R)', status:'Running for Governor — OPEN SEAT', hold:'R', open:true },
  { id:'ms-ins', tier:'Statewide executive', cat:'Other statewide', state:'Mississippi', st:'MS',
    office:'Commissioner of Insurance', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Mike Chaney (R)', status:'Eligible — intent unclear', hold:'R', open:false },

  // ---------- LEGISLATURES ----------
  { id:'la-house', tier:'State legislature', cat:'Legislature', state:'Louisiana', st:'LA',
    office:'House of Representatives — all 105 seats', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'73R / 32D', status:'19 members already not seeking re-election', hold:'R', open:false,
    note:'Kept the jungle primary — the 2024 closed-primary law excluded state legislative races.' },
  { id:'la-sen', tier:'State legislature', cat:'Legislature', state:'Louisiana', st:'LA',
    office:'State Senate — all 39 seats', general:'2027-11-20', primary:'2027-10-09', primaryConf:'confirmed',
    incumbent:'28R / 11D', status:'6 senators not seeking re-election', hold:'R', open:false },
  { id:'ms-house', tier:'State legislature', cat:'Legislature', state:'Mississippi', st:'MS',
    office:'House of Representatives — all 122 seats', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'77R / 41D / 2I', status:'Full chamber up', hold:'R', open:false },
  { id:'ms-sen', tier:'State legislature', cat:'Legislature', state:'Mississippi', st:'MS',
    office:'State Senate — all 52 seats', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'34R / 18D', status:'Full chamber up', hold:'R', open:false },
  { id:'nj-asm', tier:'State legislature', cat:'Legislature', state:'New Jersey', st:'NJ',
    office:'General Assembly — all 80 seats', general:'2027-11-02', primary:'2027-06-08', primaryConf:'projected',
    incumbent:'57D / 23R', status:'Full chamber up', hold:'D', open:false },
  { id:'nj-sen', tier:'State legislature', cat:'Legislature', state:'New Jersey', st:'NJ',
    office:'State Senate — all 40 seats', general:'2027-11-02', primary:'2027-06-08', primaryConf:'projected',
    incumbent:'25D / 15R', status:'Full chamber up', hold:'D', open:false },
  { id:'va-hod', tier:'State legislature', cat:'Legislature', state:'Virginia', st:'VA',
    office:'House of Delegates — all 100 seats', general:'2027-11-02', primary:'2027-06-15', primaryConf:'projected',
    incumbent:'64D / 36R', status:'Full chamber up', hold:'D', open:false,
    note:'Virginia moved its 2026 primary by statute — the June date is a default, not a lock.' },
  { id:'va-sen', tier:'State legislature', cat:'Legislature', state:'Virginia', st:'VA',
    office:'State Senate — all 40 seats', general:'2027-11-02', primary:'2027-06-15', primaryConf:'projected',
    incumbent:'21D / 19R', status:'Full chamber up — 21-19 majority', hold:'D', open:false },

  // ---------- JUDICIAL ----------
  { id:'wi-sc', tier:'Judicial', cat:'Judicial', state:'Wisconsin', st:'WI',
    office:'Supreme Court — Ziegler seat', general:'2027-04-06', primary:'2027-02-16', primaryConf:'confirmed',
    incumbent:'Annette Ziegler', status:'Not seeking a third term — OPEN SEAT', hold:'Nonpartisan', open:true,
    note:'Ziegler is in the conservative minority, so the majority is not at stake. Judge Pedro Colón has entered.' },
  { id:'pa-sc-todd', tier:'Judicial', cat:'Judicial', state:'Pennsylvania', st:'PA',
    office:'Supreme Court — Chief Justice retention', general:'2027-11-02', primary:null, primaryConf:'confirmed',
    incumbent:'Chief Justice Debra Todd (D)', status:'Retention (yes/no)', hold:'D', open:false,
    note:'A rejected retention creates a vacancy filled by gubernatorial appointment with two-thirds Senate confirmation.' },
  { id:'pa-sc-mundy', tier:'Judicial', cat:'Judicial', state:'Pennsylvania', st:'PA',
    office:'Supreme Court — retention', general:'2027-11-02', primary:null, primaryConf:'confirmed',
    incumbent:'Sallie Updyke Mundy (R)', status:'Retention (yes/no)', hold:'R', open:false,
    note:'The court sits 5-2 Democratic. Mundy is one of only two Republican-elected justices.' },
  { id:'pa-sup', tier:'Judicial', cat:'Judicial', state:'Pennsylvania', st:'PA',
    office:'Superior Court — 2 retention seats', general:'2027-11-02', primary:null, primaryConf:'confirmed',
    incumbent:'Deborah Kunselman (D), Carolyn Nichols (D)', status:'Retention', hold:'D', open:false,
    note:'Both took office Jan 2018 on 10-year terms. A judge declining to stand converts the seat to an open partisan race.' },
  { id:'pa-cw', tier:'Judicial', cat:'Judicial', state:'Pennsylvania', st:'PA',
    office:'Commonwealth Court — 1 retention seat', general:'2027-11-02', primary:null, primaryConf:'confirmed',
    incumbent:'Christine Fizzano Cannon (R)', status:'Retention', hold:'R', open:false,
    note:'Commonwealth Court is the court of first instance for Pennsylvania election-law challenges.' },

  // ---------- BALLOT MEASURES ----------
  { id:'la-sb68', tier:'Ballot measure', cat:'Ballot measure', state:'Louisiana', st:'LA',
    office:'SB 68 — Supreme Court disciplinary jurisdiction', general:'2027-04-17', primary:null, primaryConf:'confirmed',
    incumbent:'—', status:'CERTIFIED — the only certified 2027 measure in the country', hold:'—', open:false,
    note:'Would give the Louisiana Supreme Court jurisdiction over discipline of out-of-state attorneys.' },
];

// ---------- MAJOR LOCAL ----------
// Curated: big-city mayoralties (well sourced) plus the local races with genuine national salience.
// NOT a complete local list — see the "gaps" note on the page.
const LOCAL = [
  { id:'chi-may', tier:'Major local', cat:'Mayor', state:'Illinois', st:'IL', city:'Chicago',
    office:'Mayor', general:'2027-02-23', primary:null, primaryConf:'confirmed', runoff:'2027-04-06',
    incumbent:'Brandon Johnson (D)', status:'Undeclared — approval ~31%', hold:'Nonpartisan', open:false,
    note:'Susana Mendoza has launched a campaign. All 50 City Council wards share this ballot.' },
  { id:'phl-may', tier:'Major local', cat:'Mayor', state:'Pennsylvania', st:'PA', city:'Philadelphia',
    office:'Mayor', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Cherelle Parker (D)', status:'Undeclared', hold:'D', open:false,
    note:'Partisan; the May Democratic primary is decisive.' },
  { id:'hou-may', tier:'Major local', cat:'Mayor', state:'Texas', st:'TX', city:'Houston',
    office:'Mayor', general:'2027-11-02', primary:null, primaryConf:'projected',
    incumbent:'John Whitmire (D)', status:'Undeclared', hold:'Nonpartisan', open:false,
    note:'December runoff if no majority. All 16 council seats share the ballot.' },
  { id:'den-may', tier:'Major local', cat:'Mayor', state:'Colorado', st:'CO', city:'Denver',
    office:'Mayor', general:'2027-04-06', primary:null, primaryConf:'confirmed', runoff:'2027-06-01',
    incumbent:'Mike Johnston (D)', status:'Running', hold:'Nonpartisan', open:false,
    note:'Dates from the city’s own 2027 candidate packet. All 13 council seats share the ballot.' },
  { id:'ind-may', tier:'Major local', cat:'Mayor', state:'Indiana', st:'IN', city:'Indianapolis',
    office:'Mayor', general:'2027-11-02', primary:'2027-05-04', primaryConf:'projected',
    incumbent:'Joe Hogsett (D)', status:'Undecided after 3 terms — 3 Democrats declared', hold:'D', open:false,
    note:'Fully partisan. All 25 City-County Council seats share the ballot.' },
  { id:'nsh-may', tier:'Major local', cat:'Mayor', state:'Tennessee', st:'TN', city:'Nashville',
    office:'Mayor', general:'2027-08-05', primary:null, primaryConf:'projected',
    incumbent:'Freddie O’Connell (D)', status:'Running — launched July 2026', hold:'Nonpartisan', open:false,
    note:'Nashville votes the first Thursday in August. A state law cutting the Metro Council 40→20 was enjoined; the reduction may take effect this cycle.' },
  { id:'jax-may', tier:'Major local', cat:'Mayor', state:'Florida', st:'FL', city:'Jacksonville',
    office:'Mayor', general:'2027-05-18', primary:'2027-03-23', primaryConf:'confirmed',
    incumbent:'Donna Deegan (D)', status:'Running — filed April 2026', hold:'D', open:false,
    note:'The most competitive big-city mayoralty of 2027 — a Democratic mayor in swing Duval County with a 16R-3D council.' },
  { id:'clt-may', tier:'Major local', cat:'Mayor', state:'North Carolina', st:'NC', city:'Charlotte',
    office:'Mayor', general:'2027-11-02', primary:'2027-09-14', primaryConf:'projected', runoff:'2027-10-05',
    incumbent:'Rob Harrington (D)', status:'Not running — OPEN SEAT', hold:'D', open:true,
    note:'Vi Lyles won a 5th term in 2025 then resigned June 2026; Harrington was appointed by council and has pledged not to run.' },
  { id:'dal-may', tier:'Major local', cat:'Mayor', state:'Texas', st:'TX', city:'Dallas',
    office:'Mayor', general:'2027-11-02', primary:null, primaryConf:'projected',
    incumbent:'Eric Johnson (R)', status:'Term-limited — OPEN SEAT', hold:'R', open:true,
    note:'A 2024 charter amendment moved Dallas off the May uniform date to November of odd years.' },
  { id:'col-may', tier:'Major local', cat:'Mayor', state:'Ohio', st:'OH', city:'Columbus',
    office:'Mayor', general:'2027-11-02', primary:'2027-05-04', primaryConf:'confirmed',
    incumbent:'Andrew Ginther (D)', status:'Running for a 4th term', hold:'Nonpartisan', open:false },
  { id:'tam-may', tier:'Major local', cat:'Mayor', state:'Florida', st:'FL', city:'Tampa',
    office:'Mayor', general:'2027-03-02', primary:null, primaryConf:'projected', runoff:'2027-04-27',
    incumbent:'Jane Castor (D)', status:'Term-limited — OPEN SEAT', hold:'Nonpartisan', open:true },
  { id:'orl-may', tier:'Major local', cat:'Mayor', state:'Florida', st:'FL', city:'Orlando',
    office:'Mayor', general:'2027-11-02', primary:null, primaryConf:'projected',
    incumbent:'Buddy Dyer (D)', status:'Retiring after 6 terms — OPEN SEAT', hold:'Nonpartisan', open:true },
  { id:'kc-may', tier:'Major local', cat:'Mayor', state:'Missouri', st:'MO', city:'Kansas City',
    office:'Mayor', general:'2027-06-01', primary:'2027-04-06', primaryConf:'projected',
    incumbent:'Quinton Lucas (D)', status:'Term-limited — OPEN SEAT', hold:'Nonpartisan', open:true,
    note:'Exact June and April dates unconfirmed.' },
  { id:'ftw-may', tier:'Major local', cat:'Mayor', state:'Texas', st:'TX', city:'Fort Worth',
    office:'Mayor', general:'2027-05-01', primary:null, primaryConf:'projected',
    incumbent:'Mattie Parker (R)', status:'Undeclared', hold:'Nonpartisan', open:false },
  { id:'mem-may', tier:'Major local', cat:'Mayor', state:'Tennessee', st:'TN', city:'Memphis',
    office:'Mayor', general:'2027-10-07', primary:null, primaryConf:'projected',
    incumbent:'Paul Young (D)', status:'Undeclared', hold:'Nonpartisan', open:false,
    note:'No runoff — plurality wins. Exact October date unconfirmed. All 13 council seats share the ballot.' },
  { id:'cos-may', tier:'Major local', cat:'Mayor', state:'Colorado', st:'CO', city:'Colorado Springs',
    office:'Mayor', general:'2027-04-06', primary:null, primaryConf:'projected', runoff:'2027-05-18',
    incumbent:'Yemi Mobolade (I)', status:'Running', hold:'Independent', open:false,
    note:'One of the few genuinely competitive 2027 mayoralties — an independent in a historically Republican city.' },
  { id:'wic-may', tier:'Major local', cat:'Mayor', state:'Kansas', st:'KS', city:'Wichita',
    office:'Mayor', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Lily Wu (L)', status:'Undeclared', hold:'Libertarian', open:false,
    note:'A Libertarian big-city mayor — a genuine national rarity — in a swing city.' },
  { id:'anc-may', tier:'Major local', cat:'Mayor', state:'Alaska', st:'AK', city:'Anchorage',
    office:'Mayor', general:'2027-04-06', primary:null, primaryConf:'projected',
    incumbent:'Suzanne LaFrance', status:'Undeclared', hold:'Nonpartisan', open:false,
    note:'Runoff only if the leader falls below 45%. Competitive.' },
  { id:'tuc-may', tier:'Major local', cat:'Mayor', state:'Arizona', st:'AZ', city:'Tucson',
    office:'Mayor', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Regina Romero (D)', status:'Undeclared', hold:'D', open:false,
    note:'Unusual hybrid: partisan ward primaries, citywide general.' },
  { id:'slc-may', tier:'Major local', cat:'Mayor', state:'Utah', st:'UT', city:'Salt Lake City',
    office:'Mayor', general:'2027-11-02', primary:'2027-08-17', primaryConf:'projected',
    incumbent:'Erin Mendenhall', status:'Undeclared', hold:'Nonpartisan', open:false },
  { id:'boi-may', tier:'Major local', cat:'Mayor', state:'Idaho', st:'ID', city:'Boise',
    office:'Mayor', general:'2027-11-02', primary:null, primaryConf:'projected',
    incumbent:'Lauren McLean', status:'Undeclared', hold:'Nonpartisan', open:false },
  { id:'sav-may', tier:'Major local', cat:'Mayor', state:'Georgia', st:'GA', city:'Savannah',
    office:'Mayor', general:'2027-11-02', primary:null, primaryConf:'projected',
    incumbent:'Van Johnson (D)', status:'Term-limited — OPEN SEAT', hold:'Nonpartisan', open:true },

  // Prosecutors & election administration
  { id:'va-ca', tier:'Major local', cat:'Prosecutor', state:'Virginia', st:'VA', city:'All 95 counties',
    office:'Commonwealth’s Attorneys — county cycle', general:'2027-11-02', primary:'2027-06-15', primaryConf:'projected',
    incumbent:'Descano (Fairfax), Dehghani-Tafti (Arlington), Anderson (Loudoun, R)', status:'4-year terms, last elected 2023', hold:'Mixed', open:false,
    note:'Va. Code § 24.2-217: COUNTIES run 2023/2027; INDEPENDENT CITIES run 2025/2029. Richmond, Norfolk, Virginia Beach and Alexandria are NOT on the 2027 ballot.' },
  { id:'pa-da', tier:'Major local', cat:'Prosecutor', state:'Pennsylvania', st:'PA', city:'Allegheny & other counties',
    office:'District Attorneys — non-Philadelphia counties', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Stephen Zappala (Allegheny, R)', status:'Elected 2023 to a 7th term', hold:'Mixed', open:false,
    note:'Zappala lost the 2023 Democratic primary, then won the general as a Republican via write-in. Philadelphia’s DA is on the 2025/2029 cycle, not this one.' },
  { id:'ms-da', tier:'Major local', cat:'Prosecutor', state:'Mississippi', st:'MS', city:'~23 judicial districts',
    office:'District Attorneys', general:'2027-11-02', primary:'2027-08-03', primaryConf:'projected',
    incumbent:'Various', status:'4-year terms, last elected 2023', hold:'Mixed', open:false,
    note:'Hinds County (Jackson) is an open scandal seat — Jody Owens pleaded guilty to bribery in 2026.' },
  { id:'phl-comm', tier:'Major local', cat:'Election administration', state:'Pennsylvania', st:'PA', city:'Philadelphia',
    office:'City Commissioners — 3 seats', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Lisa Deeley (D), Omar Sabir (D), Seth Bluestein (R)', status:'On the ballot', hold:'Mixed', open:false,
    note:'The elected election administrators of the largest city in the premier presidential swing state — chosen the year before the 2028 presidential. Each voter picks two of three seats, structurally guaranteeing the minority party one seat.' },
  { id:'den-aud', tier:'Major local', cat:'Citywide office', state:'Colorado', st:'CO', city:'Denver',
    office:'Auditor', general:'2027-04-06', primary:null, primaryConf:'confirmed', runoff:'2027-06-01',
    incumbent:'Timothy O’Brien (CPA)', status:'Term-limited after 3 terms — OPEN SEAT', hold:'Nonpartisan', open:true,
    note:'Unusually powerful for a city auditor — independent watchdog over a strong-mayor system, and enforcer of Denver’s wage and labor law.' },
  { id:'den-clk', tier:'Major local', cat:'Election administration', state:'Colorado', st:'CO', city:'Denver',
    office:'Clerk & Recorder', general:'2027-04-06', primary:null, primaryConf:'confirmed', runoff:'2027-06-01',
    incumbent:'Paul López', status:'Eligible for a third term', hold:'Nonpartisan', open:false,
    note:'Runs Denver’s elections — a big-city election administrator in a swing state.' },
  { id:'hou-ctrl', tier:'Major local', cat:'Citywide office', state:'Texas', st:'TX', city:'Houston',
    office:'City Controller', general:'2027-11-02', primary:null, primaryConf:'projected',
    incumbent:'Chris Hollins', status:'First term — eligible', hold:'Nonpartisan', open:false,
    note:'Hollins ran Harris County’s 2020 election as interim County Clerk, pioneering drive-through and 24-hour voting and drawing state Republican lawsuits.' },
  { id:'chi-clk', tier:'Major local', cat:'Citywide office', state:'Illinois', st:'IL', city:'Chicago',
    office:'City Clerk & City Treasurer', general:'2027-02-23', primary:null, primaryConf:'projected', runoff:'2027-04-06',
    incumbent:'Anna Valencia (Clerk), Melissa Conyears-Ervin (Treasurer)', status:'Both re-elected unopposed in 2023', hold:'Nonpartisan', open:false,
    note:'Chicago’s only citywide elected offices besides mayor. Both ran unopposed last cycle — a contested race would itself be news.' },
  { id:'nsh-vm', tier:'Major local', cat:'Citywide office', state:'Tennessee', st:'TN', city:'Nashville',
    office:'Vice Mayor + 5 at-large Council seats', general:'2027-08-05', primary:null, primaryConf:'projected',
    incumbent:'Angie Henderson (Vice Mayor)', status:'Elected 2023', hold:'Nonpartisan', open:false,
    note:'The Vice Mayor chairs the Metro Council — the body at the center of Tennessee’s blue-city/red-state preemption fights.' },
  { id:'phl-sher', tier:'Major local', cat:'Election administration', state:'Pennsylvania', st:'PA', city:'Philadelphia',
    office:'Sheriff', general:'2027-11-02', primary:'2027-05-18', primaryConf:'projected',
    incumbent:'Rochelle Bilal (D)', status:'Re-elected 2023 with 73.7%', hold:'D', open:false,
    note:'Controller audits found 101 firearms missing from the office armory; sheriff sales were halted 2021–2024.' },
];

const NOT_HAPPENING = [
  { label:'President', why:'Next: November 2028.' },
  { label:'U.S. House — all 435 seats', why:'All seats were up in November 2026. Next: November 2028.' },
  { label:'U.S. Senate', why:'No class of senators faces a regular election in 2027. Next: November 2028.' },
];
